#!/bin/bash

# remove mention of cdrom from /etc/apt/sources.list

[ -f /etc/apt/sources.list ] && sudo mv -f /etc/apt/sources.list /etc/apt/sources.list.bak && sudo bash -c "grep -v cdrom /etc/apt/sources.list.bak > /etc/apt/sources.list"

# Add Docker's and cloudflare's official GPG key:
sudo apt-get update
sudo apt-get install ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /etc/apt/keyrings/cloudflare-main.gpg >/dev/null
sudo chmod a+r /etc/apt/keyrings/docker.asc

# Add the repository to Apt sources:
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

echo 'deb [signed-by=/etc/apt/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared any main' | sudo tee /etc/apt/sources.list.d/cloudflared.list  


# install dependencies
sudo apt update && sudo apt install -y git ansible python3-pip python3-kubernetes docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin cloudflared timeshift

# make passwordless sudo

sudo sed -i /etc/sudoers -re 's/^%sudo.*/%sudo   ALL=(ALL:ALL) NOPASSWD: ALL/g'

#bootstrap ansible
git clone https://github.com/rhildred/bootstrap /tmp/bootstrap
ansible-playbook /tmp/bootstrap/up.yml
