- name: bootstrap dev machine
  hosts: localhost
  gather_facts: false
  tasks:
  - name: download vscode
    ansible.builtin.shell: curl -L -o /tmp/vscode.deb https://go.microsoft.com/fwlink/?LinkID=760868
    args:
      creates: /tmp/vscode.deb
  - name: install vscode
    ansible.builtin.shell: dpkg -i /tmp/vscode.deb
    become: yes
    args:
      creates: /usr/bin/code
  - name: Create a user 'ubuntu' with a home diretory
    ansible.builtin.user:
      name: ubuntu
      create_home: yes
      append: true
      groups: docker,sudo
      shell: /bin/bash
    become: yes
  - name: install code-server
    ansible.builtin.shell: curl -fsSL https://code-server.dev/install.sh | sh
    args:
      creates: /usr/bin/code-server
  - name: Copy config
    ansible.builtin.copy:
      src: code-server-config.yml
      dest: /home/ubuntu/.config/code-server/config.yml
      owner: ubuntu
      group: ubuntu
  - name: make code-server a service
    ansible.builtin.shell: systemctl enable --now code-server@\ubuntu
    become: yes
    args:
      creates: /usr/lib/systemd/system/code-server@.service

  - name: download oauth2-proxy
    ansible.builtin.shell: curl -L -o /tmp/oauth2-proxy.tar.gz https://github.com/oauth2-proxy/oauth2-proxy/releases/download/v7.9.0/oauth2-proxy-v7.9.0.linux-amd64.tar.gz && tar -C /tmp -zxvf /tmp/oauth2-proxy.tar.gz && mv /tmp/oauth2-proxy-v7.9.0.linux-amd64 /usr/local
    become: yes
    args:
      creates: /usr/local/oauth2-proxy-v7.9.0.linux-amd64/
  - name: Copy service file
    ansible.builtin.copy:
      src: oauth2-proxy.service
      dest: /etc/systemd/system/oauth2-proxy.service
      owner: ubuntu
      group: ubuntu
    become: yes
