- name: bootstrap dev machine
  hosts: localhost
  gather_facts: false
  tasks:
  - name: download vscode
    ansible.builtin.shell: curl -L -o /tmp/vscode.deb https://go.microsoft.com/fwlink/?LinkID=760868
    args:
      creates: /tmp/vscode.deb
  - name: install vscode
    ansible.builtin.shell: dpkg -i /tmp/vscode.deb
    become: yes
    args:
      creates: /usr/bin/code
  - name: install code-server
    ansible.builtin.shell: curl -fsSL https://code-server.dev/install.sh | sh
    args:
      creates: /usr/bin/code-server

